name: Docker Build and Deploy to Azure Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_NAME }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}  
        
    - name: Build Backend Docker image
      run: |
        cd Back-end
        docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}/todo-backend:latest .

    - name: Build Frontend Docker image
      run: |
        cd Front-end
        docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}/todo-frontend:latest .
        
    - name: Push Docker images to Azure Container Registry
      run: |
        docker push ${{ secrets.AZURE_REGISTRY_NAME }}/todo-backend:latest
        docker push ${{ secrets.AZURE_REGISTRY_NAME }}/todo-frontend:latest

    - name: Logout from Azure Container Registry
      run: docker logout ${{ secrets.AZURE_REGISTRY_NAME }}
